image: node

pipelines:
  default:
    - step:
        script:
          - npm install
          - npm run dist -s
  branches:
    master:
      - step:
          script:
            - node deploy.js
