export {default as Buttons} from './Buttons'
export {default as Colors} from './Colors'
export {default as Controls} from './Controls'
export {default as Grid} from './Grid'
export {default as MainPage} from './MainPage'
export {default as NotFound} from './NotFound'
export {default as Papers} from './Papers'
export {default as Typo} from './Typo'